#!/usr/bin/env node
/*
 * ue-bench.mjs — synthetic-Unreal token-savings benchmark for vs-token-safer.
 *
 * Builds a throwaway UE-shaped project (Source/<Game>/<Module>/*.h/.cpp with UCLASS/UFUNCTION/UPROPERTY +
 * *.generated.h, Saved/Logs, a large working git diff, and a p4-opened fixture), then runs a realistic dev
 * "work session" — locate a class, find a symbol's uses, find files, see what changed, see what's checked
 * out, string lookup — measuring RAW tool output (grep/find/git/p4/cat) vs the vts-compacted equivalent.
 *
 *   node scripts/ue-bench.mjs [--files N] [--keep]
 *
 * No toolchain needed. NOTE: with no compile_commands.json, search_symbol/find_references run in vts's
 * TEXT-FALLBACK mode (exactly what a not-yet-Generated UE project does) — clangd-semantic mode (file:line,
 * no bodies) saves MORE; the live-verified real-depot figure is ~93%. git/p4/find/text here are full live.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";

const ARGV = process.argv.slice(2);
const flag = (n) => ARGV.includes(n);
const opt = (n, d) => { const i = ARGV.indexOf(n); return i >= 0 && ARGV[i + 1] ? ARGV[i + 1] : d; };
const NFILES = parseInt(opt("--files", "160"), 10);
const KEEP = flag("--keep");
const tok = (s) => Math.round(Buffer.byteLength(String(s), "utf8") / 4);
const CLI = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")), "..", "server", "cli.js");
const ROOT = path.join(os.tmpdir(), `vts-uebench-${process.pid}`);
const SRC = path.join(ROOT, "Source", "DemoGame");

// ---------- generate a UE-shaped tree (deterministic; no RNG) ----------
const MODULES = ["Characters", "Abilities", "Weapons", "AI", "UI", "World", "Net", "Items"];
const VERBS = ["Spawn", "Apply", "Update", "Handle", "Compute", "Resolve", "Tick", "Notify"];
function classFile(i) {
  const mod = MODULES[i % MODULES.length];
  const name = `A${mod}Actor_${i}`;
  const dir = path.join(SRC, mod);
  fs.mkdirSync(dir, { recursive: true });
  const hdr = `// Copyright DemoGame. UE-shaped synthetic file.
#pragma once
#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "${name}.generated.h"

UCLASS(BlueprintType)
class DEMOGAME_API ${name} : public AActor
{
\tGENERATED_BODY()
public:
\t${name}();
\tUPROPERTY(EditAnywhere, BlueprintReadWrite, Category="Demo") bool bIsDead = false;
\tUPROPERTY(EditAnywhere) float Health = 100.f;
\tUFUNCTION(BlueprintCallable) void TakeDamage(float Amount);
\tUFUNCTION() void ${VERBS[i % VERBS.length]}Effect();
protected:
\tvirtual void BeginPlay() override;
};
`;
  // .cpp body uses common UE idioms (GetWorld/SpawnActor/GetOwner) MANY times → grep floods on these.
  const body = [];
  body.push(`#include "${name}.h"`, `#include "Engine/World.h"`, ``);
  body.push(`${name}::${name}() { PrimaryActorTick.bCanEverTick = true; }`, ``);
  body.push(`void ${name}::BeginPlay() {`, `\tSuper::BeginPlay();`);
  for (let k = 0; k < 14; k++) {
    body.push(`\tif (GetWorld()) { UWorld* W = GetWorld(); AActor* O = GetOwner(); /* line ${k} */ }`);
    body.push(`\tGetWorld()->SpawnActor<${name}>(); // SpawnActor usage ${k}`);
  }
  body.push(`}`, ``);
  body.push(`void ${name}::TakeDamage(float Amount) {`, `\tHealth -= Amount;`, `\tif (Health <= 0.f) bIsDead = true;`, `}`, ``);
  body.push(`void ${name}::${VERBS[i % VERBS.length]}Effect() {`);
  for (let k = 0; k < 10; k++) body.push(`\tGetWorld(); GetOwner(); // ${VERBS[i % VERBS.length]} step ${k}`);
  body.push(`}`, ``);
  // generated.h stub (UE pattern)
  const gen = `// Generated by UnrealHeaderTool (synthetic stub)\n#pragma once\n` +
    Array.from({ length: 40 }, (_, k) => `#define DemoGame_${name}_${k}_GENERATED_BODY \\\n\tpublic: /* reflection glue ${k} */`).join("\n") + "\n";
  fs.writeFileSync(path.join(dir, `${name}.h`), hdr);
  fs.writeFileSync(path.join(dir, `${name}.cpp`), body.join("\n"));
  fs.writeFileSync(path.join(dir, `${name}.generated.h`), gen);
  return path.join(dir, `${name}.cpp`);
}

console.log(`Generating synthetic UE tree (${NFILES} classes) under ${ROOT} …`);
fs.mkdirSync(SRC, { recursive: true });
const cppFiles = [];
for (let i = 0; i < NFILES; i++) cppFiles.push(classFile(i));
// a fat engine-style log
fs.mkdirSync(path.join(ROOT, "Saved", "Logs"), { recursive: true });
fs.writeFileSync(path.join(ROOT, "Saved", "Logs", "DemoGame.log"),
  Array.from({ length: 6000 }, (_, i) => `[2026.06.12-04.${(i % 60).toString().padStart(2, "0")}] LogTemp: ${i % 11 === 0 ? "Error" : "Display"}: frame ${i} tick`).join("\n"));

const git = (args) => { try { return execFileSync("git", ["-C", ROOT, ...args], { encoding: "utf8", maxBuffer: 256 << 20 }); } catch (e) { return e.stdout ? String(e.stdout) : ""; } };
git(["init", "-q"]); git(["config", "user.email", "b@x.t"]); git(["config", "user.name", "b"]);
git(["config", "core.autocrlf", "false"]); git(["config", "core.safecrlf", "false"]); // no LF→CRLF warning flood
git(["add", "-A"]); git(["commit", "-qm", "initial import"]);
// simulate a feature branch edit touching ~40% of files (big working diff + status)
const edited = cppFiles.filter((_, i) => i % 5 < 2);
for (const f of edited) fs.appendFileSync(f, `\n// feature: combat rework\nvoid ${path.basename(f, ".cpp")}::Patched() { GetWorld(); bIsDead = false; }\n`);
// a few untracked new files
for (let i = 0; i < 6; i++) fs.writeFileSync(path.join(SRC, "Characters", `NewFeature_${i}.cpp`), "// wip\nGetWorld();\n");

// p4-opened fixture (no real p4 here) — a large checkout, the UE-on-Perforce reality
const p4opened = Array.from({ length: 520 }, (_, i) =>
  `//depot/DemoGame/Source/DemoGame/${MODULES[i % MODULES.length]}/A${MODULES[i % MODULES.length]}Actor_${i}.cpp#${(i % 40) + 1} - edit default change (text)`).join("\n");

// ---------- measure ----------
const rows = [];
const vts = (args) => { try { return execFileSync(process.execPath, [CLI, ...args], { encoding: "utf8", maxBuffer: 256 << 20, env: { ...process.env, VTS_ENFORCE: "0", VTS_PROJECT_PATH: ROOT } }); } catch (e) { return (e.stdout ? String(e.stdout) : "") + (e.stderr || ""); } };
const grep = (args) => { try { return execFileSync("git", ["-C", ROOT, "grep", "-n", ...args], { encoding: "utf8", maxBuffer: 256 << 20 }); } catch (e) { return e.stdout ? String(e.stdout) : ""; } };
function add(label, raw, out, note = "") { const r = tok(raw), c = tok(out); rows.push([label, r, c, r ? (100 * (1 - c / r)).toFixed(1) + "%" : "—", c ? (r / c).toFixed(1) + "×" : "∞", note]); }

// 1. locate a class (the name appears in .h decl + .cpp + generated.h → grep returns many lines, vts caps)
add("locate class (grep vs symbol)", grep(["ACharactersActor_0", "--", "*.h", "*.cpp"]), vts(["symbol", "--q", "ACharactersActor_0"]), "text-fallback (no DB)");
// 2. find every use of a hot engine call (grep floods; vts caps)
add("find uses GetWorld (grep vs text)", grep(["GetWorld", "--", "*.cpp"]), vts(["text", "--q", "GetWorld"]), "capped");
// 3. find a UFUNCTION across the tree
add("find UFUNCTION TakeDamage", grep(["TakeDamage", "--", "*.cpp", "*.h"]), vts(["symbol", "--q", "TakeDamage"]), "text-fallback");
// 4. find files by name
add("find files *Actor_1*.h", (function () { try { return execFileSync("find", [path.join(SRC), "-name", "*Actor_1*.h"], { encoding: "utf8" }); } catch (e) { return e.stdout || ""; } })(), vts(["files", "--q", "*Actor_1*.h"]));
// 5. what changed — git status + diff
add("git status (post-edit)", git(["status"]), vts(["git", "status"]).replace(/\n\n✓ Saved[\s\S]*$/, ""));
add("git diff (working set)", git(["diff"]), vts(["git", "diff"]).replace(/\n\n✓ Saved[\s\S]*$/, ""));
// 6. what's checked out — p4 opened (fixture through the compactor)
const { compactP4 } = await import("../server/compact.js");
add("p4 opened (520 files)", p4opened, compactP4("opened", p4opened, 60));
// 7. config/flag lookup
add("string lookup bIsDead", grep(["bIsDead", "--", "*.cpp", "*.h"]), vts(["text", "--q", "bIsDead"]), "capped");

// ---------- report ----------
const pad = (s, n) => String(s).padEnd(n), padL = (s, n) => String(s).padStart(n);
console.log("");
console.log(pad("UE work-session scenario", 34) + padL("raw", 8) + padL("vts", 7) + padL("saved", 8) + padL("ratio", 8) + "  note");
console.log("-".repeat(86));
let tr = 0, tc = 0;
for (const [l, r, c, p, x, note] of rows) { console.log(pad(l, 34) + padL(r, 8) + padL(c, 7) + padL(p, 8) + padL(x, 8) + "  " + note); tr += r; tc += c; }
console.log("-".repeat(86));
console.log(pad("TOTAL (one dev session)", 34) + padL(tr, 8) + padL(tc, 7) + padL((100 * (1 - tc / tr)).toFixed(1) + "%", 8) + padL((tr / tc).toFixed(1) + "×", 8));
console.log(`\nLog steer: a grep over Saved/Logs/DemoGame.log (${tok(fs.readFileSync(path.join(ROOT, "Saved", "Logs", "DemoGame.log"), "utf8")).toLocaleString()} tok raw) is routed to gamedev-log, not the index.`);
console.log("Symbol rows are TEXT-FALLBACK (no compile_commands.json). clangd-semantic mode saves more (~93% live-verified on a real depot).");

if (!KEEP) { try { fs.rmSync(ROOT, { recursive: true, force: true }); } catch { /* ignore */ } }
else console.log(`\n--keep: tree left at ${ROOT}`);
